# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fourier terms
NULL

GenFT <- function(time_counter, K, period) {
    .Call(`_ElecForecast_GenFT`, time_counter, K, period)
}

rbf_kernel <- function(X, l, sigma) {
    .Call(`_ElecForecast_rbf_kernel`, X, l, sigma)
}

RidgeReg <- function(X, y, lambda) {
    .Call(`_ElecForecast_RidgeReg`, X, y, lambda)
}

RidgeRegPar <- function(X, y, lambda) {
    .Call(`_ElecForecast_RidgeRegPar`, X, y, lambda)
}

parallel_ridge_cross_validation <- function(x_vars, y_var, time_counter, daily_period, annual_period, max_K, lambda_values, n_folds) {
    .Call(`_ElecForecast_parallel_ridge_cross_validation`, x_vars, y_var, time_counter, daily_period, annual_period, max_K, lambda_values, n_folds)
}

predict_parallel_ridge_cv <- function(model, x_test, y_test, time_counter, daily_period, annual_period) {
    .Call(`_ElecForecast_predict_parallel_ridge_cv`, model, x_test, y_test, time_counter, daily_period, annual_period)
}

parallel_ridge_cross_validation2 <- function(x_vars, y_var, time_counter, daily_period, annual_period, max_K, lambda_values, n_folds) {
    .Call(`_ElecForecast_parallel_ridge_cross_validation2`, x_vars, y_var, time_counter, daily_period, annual_period, max_K, lambda_values, n_folds)
}

