# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fourier terms
#'
#' @description Generate Fourier terms
#'
#' @param time_counter Vector of time counter
#' @param K Maximum order of Fourier terms
#' @param period Number of time increments per period
#'
#' @return Matrix of the Fourier terms
#' @export
#'
generate_fourier_terms <- function(time_counter, K, period) {
    .Call(`_ElecForecast_generate_fourier_terms`, time_counter, K, period)
}

parallel_ridge_cross_validation <- function(x_vars, y_var, time_counter, daily_period, annual_period, max_K, n_folds, alpha = 0) {
    .Call(`_ElecForecast_parallel_ridge_cross_validation`, x_vars, y_var, time_counter, daily_period, annual_period, max_K, n_folds, alpha)
}

rcpp_hello_world <- function() {
    .Call(`_ElecForecast_rcpp_hello_world`)
}

performRidgeRegression <- function(X, y, lambda) {
    .Call(`_ElecForecast_performRidgeRegression`, X, y, lambda)
}

parallelRidgeCV <- function(X, y, lambda_values) {
    .Call(`_ElecForecast_parallelRidgeCV`, X, y, lambda_values)
}

